### ISSUE TITLE
Latest version 1.4.1 broke installations

### ISSUE THREAD

**Issue by uda** [moviedo/ansible-role-nvm#14]
Since you used vN.N.N until now, and the latest 1.4.1 is in the same syntax, the CLI can't determine which version is the latest, I guess you'll need to remove 1.4.1 and re-release as v1.4.1.

**Comment by sylvainmetayer** [comment]
I'm having the same issue

**Comment by uda** [comment]
I worked around it for now by specifying the version

In CLI
```
ansible-galaxy install moviedo.nvm,1.4.1
```

In requirements.yml
```
- src: moviedo.nvm
  version: 1.4.1
```

**Comment by moviedo** [comment]
Fixed the tag issue.
